server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ff514519
    url: jdbc:mysql://localhost:3306/securitydemo?serverTimezone=GMT%2B8&useSSL=true
    username: root
