spring:
  datasource:
    druid:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: test
      password: ff514519
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss