server:
  port: 8081
spring:
  application:
    name: ihrm-company #指定服务名
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm_shiro_db?serverTimezone=GMT%2B8
    username: root
    password: ff514519
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379