spring:
  datasource:
    druid:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username:
      password:
      url: jdbc:oracle:thin:@10.2.0.42:1521:lis
      db-type: Oracle
schema:
  pdm-filename:
  db-username:
  op-flag: DB
  package-name:
  output-path:
  output-package-path:
  table-name: ""
